export enum BotState {
  IDLE = 'IDLE',
  LISTENING = 'LISTENING',
  THINKING = 'THINKING',
  SPEAKING = 'SPEAKING',
  ERROR = 'ERROR',
  INITIALIZING = 'INITIALIZING',
  NO_MIC_PERMISSION = 'NO_MIC_PERMISSION'
}
